
name: aseprite-auto-built

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to build, leave empty for latest"
        required: false

jobs:
  build:
    runs-on: windows-2022
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        id: build
        shell: cmd
        run: call build.cmd
        env:
          ASEPRITE_VERSION: ${{ github.event.inputs.version }}
      
      - name: Archive
        uses: actions/upload-artifact@v4
        with:
          name: aseprite-${{ steps.build.outputs.ASEPRITE_VERSION }}
          path: github
          if-no-files-found: error
      
      - name: GH Release
        uses: softprops/action-gh-release@v2
        with:
          name: aseprite-${{ steps.build.outputs.ASEPRITE_VERSION }}
          tag_name: ${{ steps.build.outputs.ASEPRITE_VERSION }}
          files: |
            aseprite-${{ steps.build.outputs.ASEPRITE_VERSION }}.zip
