name: RENEW
on:
  schedule:
    - cron: '0 0 1,5,15,25,30 * *'
  workflow_dispatch:
    inputs:
      name:
          description: 'Run?'
          required: true
          default: 'YES!'

  pull_request:
  pull_request_target:

permissions:
  contents: write
  pull-requests: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
      - name: Create local changes
        run: |
          echo $(date +'%d-%m-%y') >> keep_active_repo
      
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          author_name: "MinhCreator"
          github_token: ${{ secrets.PAT }}
          message: "renew repo in $(date +'%d-%m-%y')"

      - name: trigger build
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT }}
          event-type: build